export default {
	empty: 'https://wx.sunsirs.cn/Public/memu/data1.png',
	pageBg: '#f8f8f8',
	boxBg: '#fff',
	boxBgTop: '#fff',
	boxBgBottom: '#ecf4ff',
	navBg: '#fff',
	tabBg: '#fff',
	cardBg: '#ede9ff',
	baseText: '#000',
	pageText: '#333',
	pageTextSub: '#999',
	navText: '#333',
	tabText: '#666',
	light_btn: '#007aff',
	light_btn2: '#c3bbff',
	tabTextActive: '#007aff', //'#007aff',
	tabTextInactive: '#999',
	dataText: '#007aff',
	redText: '#fa2d47',
	greenText: '#01c301',
	frontColor: '#000000',
	themeIcon: 'custom-icon-baitianmoshi',
	themeIconColor: '#eabb5d',
	boxShadow: '0px 1px 10px 10px rgba(200, 200, 200, 0.1)',
	mask: 'rgba(255,255,255,.8)',
	warn: '#ff8100',
	error: '#ef495b',
	loading: '#9cb6ef',
	badgeBg: '#007aff',
	lineColor: '#f8f8f8',
	followCard: {
		boxTopBg: '#fff',
		boxBottomBg: '#fff',
		boxCardBg: '#f7f6ff',
		btnBg: '#668bf8',
		btnText: '#fff',
		boxBottomText: '#999',
		titleText: '#000',
		iconText: '#007aff',
		baseText: '#000',
		subText: '#999',
		indicatorColor: '#efefef',
		indicatorActiveColor: '#9cb6ef'
	},
	hqCard: {
		hqBg: '#fff',
		cardTopBg: '#f7f6ff',
		cardBottomBg: '#f7f6ff',
		baseText: '#000',
	},
	marketCardTabs: {
		iconText: '#6389f7',
		itemStyle: {
			backgroundColor: '#fff',
			color: '#000',
			borderRadius: '10rpx'
		}
	},
	marketCard: {
		boxBg: '#007aff',
		tBg: '#dde9ff',
		boxBgTop: '#ecf4ff',
		boxBgBottom: '#fff',
		boxShadow: '0 0 10rpx rgba(0,0,0,.1)',
		subText: '#333',
		label_bg: '#fff',
		label_s: '#ff0000',
		label_b: '#007aff',
	},
	pan: {
		tagcolor: '#9dc4ff',
		lightcolor: '#ffb70e',
		imgBtn: '#ffb100',
		pageBg: '#f8f8f8',
		boxBg: '#f3f6fe',
		boxBgTop: '#fff',
		boxBgBottom: '#ecf4ff',
		navBg: '#fff',
		tabBg: '#fff',
		cardBg: '#ede9ff',
		baseText: '#000',
		pageText: '#333',
		pageTextSub: '#999',
		tabBgActive: '#fff',
		tabBgInactive: '#fff',
		tabTextActive: '#007aff',
		tabTextInactive: '#8790ab',
		headerBg: '#007aff',
		headerText: '#fff',
		headerSubText: '#d3e6ff'
	},
	search: {
		tagBg: '#e8e8e8',
		tagBorder: '#e4e4e4',
		tagText: '#888',
		tagClose: '#ccc',
		activeColor: '#007aff',
		inactiveColor: '#666',
	}
	
}
